import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Inngest Demo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Inngest demo app</h1>

        <p className={styles.description}>
          Head over to{" "}
          <Link href="/api/inngest">
            <a>
              <code>/api/inngest</code>
            </a>
          </Link>{" "}
          to inspect all configured functions
        </p>

        <div className={styles.grid}>
          <a href="https://www.inngest.com/docs" className={styles.card}>
            <h2>Inngest Documentation &rarr;</h2>
          </a>

          <a href="https://www.inngest.com/blog" className={styles.card}>
            <h2>Inngest Blog &rarr;</h2>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
